version: '2'
services:

  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017/hackathon"

  mongo:
    image: mongo:3
    command: mongod --smallfiles
    networks:
      - all

networks:
  all: